
services:
 
  foyer-app:
    image:  nourchawebi/foyer-app:1.1.138
    ports:
      - "8089:8089"


    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db?createDatabaseIfNotExist=true  # Updated DB URL
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  db:
    image: mysql:latest  
    environment:
      MYSQL_ROOT_PASSWORD: "root"  
      MYSQL_DATABASE: db  # Crée la base de données lors du démarrage
    ports:
      - "3306:3306"  # Mappe le port 3306 de MySQL au port 3306 de l'hôte
    volumes:
      - db_data:/var/lib/mysql  # Persiste les données de MySQL

volumes:
  db_data:  # Définit un volume nommé pour persister les données
