services:
  foyer-app:
    image: nourchawebi/foyer-app:1.1.150
    ports:
      - "8089:8089"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db?createDatabaseIfNotExist=true 
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "root"
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      # Actuator and Prometheus settings
      MANAGEMENT_ENDPOINTS_WEB_BASE_PATH: /actuator
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
      MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: true

  db:
    image: mysql:latest  
    environment:
      MYSQL_ROOT_PASSWORD: "root"  
      MYSQL_DATABASE: db  
    ports:
      - "3306:3306"  
    volumes:
      - db_data:/var/lib/mysql  

volumes:
  db_data:
